### ISSUE TITLE
overrident variables appearing as NaN

### ISSUE THREAD

**Issue by pcfleischer** [getinsomnia/insomnia.rest#13]
When setting up a base environment with a list of OAuth clients, the variables which should be overridden as shown in preview are actually returning "NaN".  Even when directly defining an overridden variable it's still resolving to "NaN"

*Base Environment*
```
	"env": {
		"clients": {
			"client-1": {
				"secret": ""
			}
		},
	},
       	"clients": {
		"client-1": {
			"id": "client-1"
			"secret": "env.clients.client-1.secret"
		}
	}
```

*Test Environment*
```
	"env": {
		"clients": {
			"client-1": {
				"secret": "12345"
			}
		},
	}
```

If I select clients.client-1.secret the "preview" shows "12345" but when I either show the tooltip or actually capture the request using charles proxy i see *NaN*.  Even when I specify "env.clients.client-1.secret" it still doesn't resolve.

I'm attempting to not have to define the entire client on every environment.  Right now it looks like my only option is to fully define everything for every environment and "Base Environment" won't work.

https://puu.sh/x9rT5/955978ce61.png

**Comment by gschier** [comment]
You're not allowed `-` in variable names. There is a warning if you do this on a top-level variable but the warning isn't implemented for nested variables.

A bit of explanation: Insomnia uses Nunjucks templating under the hood. Referencing `{{ clients.client-1.secret }}` actually means `clients.client` SUBTRACT `1.secret`. Since neither of those are defined, it results in `NaN`.

**Comment by gschier** [comment]
Also, for future reference, issues regarding the app should be posted in the app repo https://github.com/getinsomnia/insomnia/issues

**Comment by pcfleischer** [comment]
yep that was it, thanks, my bad on the wrong repo.
