### ISSUE TITLE
Huge images

### ISSUE THREAD

**Issue by janpio** [getinsomnia/insomnia.rest#8]
I am on a very slow connection right now and had to watch the screens on the homepage load quite slowly. Is there a reason the images are many sizes bigger than they are dispayed (example: https://insomnia.rest/images/screens/main.png)? 

You can't click them to zoom in, so they could probably scaled down.

**Comment by gschier** [comment]
It's like that so the images are crisp on retina displays. I haven't had time yet to implement "responsive images."

Since the screenshots are PNG with low detail they are already pretty small (~50KB each). Making them smaller would be a pretty small win compared to the amount of work required.

One day... 😉

**Comment by gschier** [comment]
Hmm, just tried halving the size. Savings are larger than I expected at `54KB` to `23KB`.

**Comment by janpio** [comment]
https://webspeedtest.cloudinary.com/results/171122_5N_0a32fcf2bf88f82e8739e87b6e59ae43
322.0 KB => 84.7 KB
;)

**Comment by gschier** [comment]
Alright, I resized the images to double their display size. Got it down to 180KB https://webspeedtest.cloudinary.com/results/171122_SJ_e1ca942763de148533c25113ef5ca3dc

**Comment by janpio** [comment]
👍

**Comment by gschier** [comment]
Haha. Thanks for making me do that 😄
